### ISSUE TITLE
metadata update error under node version >= 7.0.3

### ISSUE THREAD

**Issue by fortunado** [halt-hammerzeit/libphonenumber-js#8] opened 2017-01-07 11:56 UTC
Hi,

Just caught an error while building custom metadata:
```
> secret-frontend@0.0.1 postinstall /Users/user/Documents/Projects/secret-frontend
> libphonenumber-generate-metadata ./app/js/utils/libs/libphonenumber-metadata.json --countries RU --extended

Metadata path: /Users/user/Documents/Projects/secret-frontend/app/js/utils/libs/libphonenumber-metadata.json
Included countries: [ 'RU' ]
Include extra validation regular expressions
/Users/user/Documents/Projects/secret-frontend/node_modules/libphonenumber-js/bin/update-metadata.js:43
download('https://raw.githubusercontent.com/googlei18n/libphonenumber/master/resources/PhoneNumberMetadata.xml')
^

TypeError: download is not a function
    at Object.<anonymous> (/Users/user/Documents/Projects/secret-frontend/node_modules/libphonenumber-js/bin/update-metadata.js:43:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

Fixed by adding `.default` to imports in `bin/update-metadata`:
```
var download = require('../build/tools/download').default
var generate = require('../build/tools/generate').default
var compress = require('../build/tools/compress').default
```

Command was called as:
`"postinstall": "libphonenumber-generate-metadata ./app/js/utils/libs/libphonenumber-metadata.json --countries RU --extended"`

Node:
```
10:secret-frontend user$ node -v
v7.3.0
10:secret-frontend user$ npm -v
4.0.5
```

Thank you for this lib very much!

**Comment by halt-hammerzeit** [comment] 2017-01-07 12:25
Hmm.
That's strange because download should work without `.default`.
https://unpkg.com/libphonenumber-js@0.2.27/build/tools/download.js
Are you sure you have the latest version installed?
`npm install libphonenumber-js@latest`

**Comment by fortunado** [comment] 2017-01-07 15:51
Yes, the latest:

```
10:secret-frontend user$ npm list libphonenumber-js
secret-frontend@0.0.1 /Users/user/Documents/Projects/secret-frontend
├── UNMET PEER DEPENDENCY eslint-plugin-jsx-a11y@3.0.2 extraneous
└── libphonenumber-js@0.2.27
```

```
10:secret-frontend user$ cat ./node_modules/libphonenumber-js/package.json | grep version
    "metadata:publish": "npm version patch && npm publish && git push", 
    "version": "0.2.27"
```

**Comment by halt-hammerzeit** [comment] 2017-01-12 09:57
You were right, this bug is confirmed.
Should be fixed in the latest version.

**Closed** 2017-01-12 09:56 UTC
